##
## EPITECH PROJECT, 2024
## git controller library
## File description:
## makefile for the git controller library
##

## PROJECT
PROJECT_REL_PATH		:= ../..
PROJECT_LIB_MAKEFILE_NAME	:= LibraryMakefile.mk
PROJECT_LIB_MAKEFILE		:= $(PROJECT_REL_PATH)/$(PROJECT_LIB_MAKEFILE_NAME)

## Name
LIB_NAME	:= git-controller

## Folders and non changing names
SRC_FOLDER	:= src
SRC_LIST	:= src.mk
HEADER_FOLDER	:= include
TEST_FOLDER	:= tests
TEST_SRC_LIST	:= test_src.mk
VERSION_FILE	:= version.txt

-include $(PROJECT_LIB_MAKEFILE)
